### ISSUE TITLE
When will you support 4.26

### ISSUE THREAD

**Issue by cabbagehao** [tomlooman/StealthGameUdemy#14]
I got an error when open the code with Unreal Engine 4.26.
> Engine modules are out of date, and cannot be compiled while the engine is running. Please build through your IDE.

Would you support 4.26 in the near future?

**Comment by tomlooman** [comment]
That message will always pop-up when it's compiled with an older version or if it hasn't been compiled yet at all, you'll just need to compile it (through Visual Studio) and see what's incompatible if anything.

**Comment by cabbagehao** [comment]
My environment: macOS Big Sur 11.1, Unreal Engine 4.26 (compiled from the source code), Xcode 12.3
I have created a new FPS project and compiled it successfully.
After I cloned this repo and double click the FPSGame.uproject, I got this error:
![image](https://user-images.githubusercontent.com/8425720/105736544-e00eb180-5f6f-11eb-93aa-e601610ebaa3.png)
![image](https://user-images.githubusercontent.com/8425720/105736610-f3218180-5f6f-11eb-9623-b5592b559c81.png)
Do you have any suggestions? Thanks.

**Comment by tomlooman** [comment]
You don't need unreal from source BTW, you can just use the launcher. All you need for this project to work is rightclick to "generate visual studio project files" and then the .sln is used to open and compile the project. It's a little different on Mac with XCode or VSCode, but the general process is the same.

**Comment by cabbagehao** [comment]
I have found the `Generate Xcode project` in the right-click menu, it's at the bottom of the menu.
Thank you very very much.
BTW, I have tried to install UE4.26 / UE4.25 / UE4.26-chaos, None of them can compile C++ by Xcode. 
So I chose to compile UE from the source. It works well now. ^_^
