### ISSUE TITLE
4.19

### ISSUE THREAD

**Issue by j** [tomlooman/StealthGameUdemy#4]
Just wondering if something changed when using "NotifyActorBeginOverlap".

I'm going through the tutorial and this method over-ride is not being called.  It works if I allow the root component to have collision though.

Is this something on my end?

**Comment by tomlooman** [comment]
Sorry for not seeing this sooner, in 4.19 nothing changed for the notify overlap function. I just added new branches for 4.19 and 4.20 support btw
