### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by ghost** [tomlooman/StealthGameUdemy#8]
I tried to run the code because the one I made got corrupted and lost all my progress. When I try to run the code I got this error1:
>D:\Downloads\StealthGame\StealthGameUdemy-master\Source\FPSGame\Private\FPSAIGuard.cpp(8): fatal error C1083: Cannot open include file: 'AI/Navigation/NavigationSystem.h': No such file or directory.
Can someone tell me how to resolve this issue and by the way I haven't changed anything since extracting it and trying to tun the code.

**Comment by 0xunreal** [comment]
https://docs.unrealengine.com/en-US/Builds/4_20#programmingupgradenotes explains it. You have to do the folllowing:
- include "NavigationSystem" module in .Build.cs
- change line #include "AI/Navigation/NavigationSystem.h" to #include "NavigationSystem.h"
- change UNavigationSystem::SimpleMoveToActor(GetController(), CurrentPatrolPoint); to UNavigationSystemV1::SimpleMoveToActor(GetController(), CurrentPatrolPoint);

**Comment by thejinchao** [comment]
SimpleMoveToActor is deprecated. Use UAIBlueprintHelperLibrary::SimpleMoveToActor instead

1. `#include "Blueprint/AIBlueprintHelperLibrary.h"`
2.  change  `UNavigationSystem::SimpleMoveToActor(GetController(), CurrentPatrolPoint); ` to 	 `UAIBlueprintHelperLibrary::SimpleMoveToLocation(GetController(), CurrentPatrolPoint->GetActorLocation());`

**Comment by tomlooman** [comment]
I've added a new branch to add support for 4.20, this to keep the original versions alive too.

**Comment by pbasson** [comment]
I can confirm that for Unreal version 4.22, @thejinchao mentioned fix is indeed working and valid.

**Comment by allyjunio** [comment]
I can confirm that for Unreal version 4.25.1, @tomlooman mentioned fix is indeed working and valid using branch https://github.com/tomlooman/StealthGameUdemy/tree/UE-4.25

**Comment by lxhhuangjin** [comment]
> SimpleMoveToActor is deprecated. Use UAIBlueprintHelperLibrary::SimpleMoveToActor instead
> 
> 1. `#include "Blueprint/AIBlueprintHelperLibrary.h"`
> 2. change  `UNavigationSystem::SimpleMoveToActor(GetController(), CurrentPatrolPoint); ` to 	 `UAIBlueprintHelperLibrary::SimpleMoveToLocation(GetController(), CurrentPatrolPoint->GetActorLocation());`

I tried this code. But got this error:
>error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static void __cdecl UAIBlueprintHelperLibrary::SimpleMoveToLocation(class AController *,struct FVector const &)" (__imp_?SimpleMoveToLocation@UAIBlueprintHelperLibrary@@SAXPEAVAController@@AEBUFVector@@@Z)
